### ISSUE TITLE
Installation always fails

### ISSUE THREAD

**Issue by sounisi5011** [christophehurpeau/check-package-dependencies#472]
The `bin` field in the `package.json` file has the following values:

https://github.com/christophehurpeau/check-package-dependencies/blob/49bb8ed58ce7b0d4e587d4157e8715def61efe7c/package.json#L28

However, the files that actually exist [in the `bin` directory are `check-package-dependencies.mjs`](https://github.com/christophehurpeau/check-package-dependencies/blob/v6.2.1/bin/check-package-dependencies.mjs).
Due to this filename mismatch, `check-package-dependencies` installations will always fail.

```console
$ npm i -DE check-package-dependencies
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path $PROJECT_DIR/node_modules/check-package-dependencies/bin/check-package-dependencies.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '$PROJECT_DIR/node_modules/check-package-dependencies/bin/check-package-dependencies.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     $HOME/.npm/_logs/2023-03-08T16_16_17_288Z-debug.log
```

**Comment by christophehurpeau** [comment]
Thank you for this report :) Please confirm latest release fixes it for you 🙏
